controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint", "rear_back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint", "rear_back_right_wheel_joint"]
    wheel_separation: 0.45
    wheel_radius: 0.07  # Matches diameter 0.14
    base_frame_id: base_link
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    max_angular_vel: 3.0  <!-- Matches Nav2 for fast turning -->
    max_angular_accel: 6.0  <!-- Increased for responsiveness -->
    enable_odom_tf: true

gripper_controller:
  ros__parameters:
    joints:
      - gripper_vertical_joint
      - gripper_finger_left_joint
      - gripper_finger_right_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      gripper_vertical_joint: {p: 100.0, d: 10.0}
      gripper_finger_left_joint: {p: 100.0, d: 10.0}
      gripper_finger_right_joint: {p: 100.0, d: 10.0}